
USER_AUTHENTICATION_QUERY = "SELECT USER_NAME FROM USER_AUTH WHERE USER_ID=%s AND USER_PWD=%s"

USER_SIGNUP_QUERY = "INSERT INTO USER_AUTH VALUES(%s,%s,%s)"

USER_CHECK_QUERY = "SELECT USER_NAME FROM USER_AUTH WHERE USER_ID=%s"

ALL_LOCATIONS_QUERY = "SELECT HORI, VERT, SERVICE_NAME, UNIQUE_NO, MAPPING.SERVICE_NO " \
                       "FROM  MAPPING, SERVICE_LIST " \
                       "WHERE MAPPING.SERVICE_NO = SERVICE_LIST.SERVICE_NO " \
                           "ORDER BY VERT, HORI"
                           
ROUTE_QUERY = "SELECT ROUTE FROM MAP_ROUTE " \
              "WHERE MAP_ROUTE.SRC=%s AND MAP_ROUTE.DEST=%s"
